Repository jenkinsci/analysis-model, pull requests merged in 2019-10, with the labels that each got.

#224 Revert PMD version to 6.17.0
  pom.xml
Labels: dependencies

#232 [JENKINS-59440] Add support for multi-module maven builds
  src/main/java/edu/hm/hafner/analysis/parser/MavenConsoleParser.java
  src/test/java/edu/hm/hafner/analysis/parser/MavenConsoleParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/maven-multimodule.log
Labels: enhancement, hacktoberfest

#233 [JENKINS-57428] Ignore errorprone warnings in the javac-parser
  pom.xml
  src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java
  src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/javac-errorprone.txt
Labels: enhancement, hacktoberfest

#234 Replace Travis with GitHub actions
  .github/workflows/maven.yml
  .travis.yml
  README.md
Labels: internal

#235 Delete deprecated base classes
  src/main/java/edu/hm/hafner/analysis/FastRegexpLineParser.java
  src/main/java/edu/hm/hafner/analysis/RegexpDocumentParser.java
  src/main/java/edu/hm/hafner/analysis/RegexpParser.java
Labels: removed

#231 Add missing Modelsim error
  src/main/java/edu/hm/hafner/analysis/Severity.java
  src/main/java/edu/hm/hafner/analysis/parser/MentorParser.java
  src/test/java/edu/hm/hafner/analysis/parser/MentorParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/modelsim.log
Labels: enhancement

#236 Add parser for protolint
  src/main/java/edu/hm/hafner/analysis/parser/ProtoLintParser.java
  src/test/java/edu/hm/hafner/analysis/parser/ProtoLintParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/protolint.txt
Labels: enhancement

#239 Fix some warnings
  .github/workflows/maven.yml
  src/test/java/edu/hm/hafner/util/ResourceTest.java
Labels: internal
