Repository jenkinsci/analysis-model, pull requests merged in 2020-08, with the labels that each got.

#486 [AntJavaParser] Ignore warnings that contain a `@` symbol
  src/main/java/edu/hm/hafner/analysis/parser/AntJavacParser.java
  src/test/java/edu/hm/hafner/analysis/parser/AntJavacParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue63346.txt
Labels: bug

#483 Use new `buildPlugin` shared library
  Jenkinsfile
  pom.xml
Labels: internal

#500 [JENKINS-63527] Create a test case that exposes the bug
  src/test/java/edu/hm/hafner/analysis/parser/violations/JUnitAdapterTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/violations/report.junit
Labels: bug, tests

#503 Add support for parsing Kotlin errors
  src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java
  src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/kotlin-gradle-error.txt
Labels: enhancement
