Repository jenkinsci/analysis-model, pull requests merged in 2020-07, with the labels that each got.

#458 Add benchmark tests
  pom.xml
  src/test/java/edu/hm/hafner/ArchitectureTest.java
  src/test/java/edu/hm/hafner/analysis/AbstractBenchmark.java
  src/test/java/edu/hm/hafner/analysis/FingerprintGeneratorBenchmark.java
  src/test/java/edu/hm/hafner/analysis/PackageNameResolverBenchmark.java
  src/test/resources/edu/hm/hafner/analysis/fingerprint.txt
Labels: tests

#459 Add benchmark test for serialization
  src/test/java/edu/hm/hafner/analysis/ReportSerializationBenchmark.java
Labels: tests

#469 Add parser benchmark test
  Jenkinsfile
  src/test/java/edu/hm/hafner/analysis/AbstractBenchmark.java
  src/test/java/edu/hm/hafner/analysis/FingerprintGeneratorBenchmark.java
  src/test/java/edu/hm/hafner/analysis/IssueDifferenceBenchmark.java
  src/test/java/edu/hm/hafner/analysis/PackageNameResolverBenchmark.java
  src/test/java/edu/hm/hafner/analysis/ReportSerializationBenchmark.java
  src/test/java/edu/hm/hafner/analysis/parser/ParserBenchmark.java
Labels: tests

#466 Adding support for hadolint json files
  pom.xml
  src/main/java/edu/hm/hafner/analysis/parser/HadoLintParser.java
  src/test/java/edu/hm/hafner/analysis/parser/HadoLintParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/hadolint-unsual.json
  src/test/resources/edu/hm/hafner/analysis/parser/hadolint.json
Labels: feature

#475 Add Flawfinder Parser
  src/main/java/edu/hm/hafner/analysis/parser/FlawfinderParser.java
  src/test/java/edu/hm/hafner/analysis/parser/FlawfinderParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/flawfinder.log
Labels: feature

#477 Convert RuboCop Parser to use named groups
  src/main/java/edu/hm/hafner/analysis/parser/RuboCopParser.java
Labels: internal

#476 Add package detector for Kotlin files
  pom.xml
  src/main/java/edu/hm/hafner/analysis/AbstractPackageDetector.java
  src/main/java/edu/hm/hafner/analysis/CSharpNamespaceDetector.java
  src/main/java/edu/hm/hafner/analysis/JavaPackageDetector.java
  src/main/java/edu/hm/hafner/analysis/KotlinPackageDetector.java
  src/main/java/edu/hm/hafner/analysis/PackageDetectors.java
  src/test/java/edu/hm/hafner/analysis/KotlinPackageDetectorTest.java
  src/test/resources/edu/hm/hafner/analysis/MavenKotlinTest.txt
  src/test/resources/edu/hm/hafner/analysis/complicated-package-declaration-kotlin.txt
Labels: feature
