Repository jenkinsci/analysis-model, pull requests merged in 2021-01, with the labels that each got.

#549 [JENKINS-55733] - CppCheck parser ignores errors without location.
  pom.xml
  src/test/java/edu/hm/hafner/analysis/parser/violations/CppCheckAdapterTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/violations/issue64519.xml
Labels: bug, tests

#546 [JENKINS-63532] Add a parser for translation files of Qt
  src/main/java/edu/hm/hafner/analysis/parser/QtTranslationParser.java
  src/test/java/edu/hm/hafner/analysis/parser/QtTranslationParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/duplicatedName.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/duplicatedSource.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/duplicatedTranslation.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/missingElementStart.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/missingName.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/missingSource.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/missingTranslation.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/multilineTranslation.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/rootElementHasParent.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/shouldParseAllIssues.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/shouldParseAllIssuesSingleLine.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/unknownTranslationType.ts
  src/test/resources/edu/hm/hafner/analysis/parser/qttranslation/wrongParent.ts
Labels: feature

#554 Simplify NAG fortran parser tests
  src/main/java/edu/hm/hafner/analysis/parser/NagFortranParser.java
  src/test/java/edu/hm/hafner/analysis/parser/NagFortranParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/NagFortran.txt
  src/test/resources/edu/hm/hafner/analysis/parser/NagFortranExtensionF2008.txt
  src/test/resources/edu/hm/hafner/analysis/parser/NagFortranExtensionF2018.txt
  src/test/resources/edu/hm/hafner/analysis/parser/NagFortranExtensionNAG.txt
  src/test/resources/edu/hm/hafner/analysis/parser/NagFortranNonStandardObsolete.txt
Labels: internal

#555 Avoid working with `null` references
  src/main/java/edu/hm/hafner/analysis/IssueDifference.java
Labels: internal

#553 Improve runtime of delta computation
  src/main/java/edu/hm/hafner/analysis/IssueDifference.java
Labels: bug

#556 RuboCop Parser: Parse lines with '[Correctable]' addition
  src/main/java/edu/hm/hafner/analysis/parser/RuboCopParser.java
  src/test/java/edu/hm/hafner/analysis/parser/RuboCopParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/rubocop.log
Labels: bug

#557 Fix parsing of ArchUnit test results
  pom.xml
  src/test/java/edu/hm/hafner/analysis/parser/violations/JUnitAdapterTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/violations/TEST-Aufgabe3Test.xml
Labels: bug, tests
