Repository jenkinsci/analysis-model, pull requests merged in 2021-02, with the labels that each got.

#559 [JENKINS-64657] Create a DoxygenParser based on the existing GccParser
  src/main/java/edu/hm/hafner/analysis/parser/DoxygenParser.java
  src/main/java/edu/hm/hafner/analysis/parser/Gcc4CompilerParser.java
  src/test/java/edu/hm/hafner/analysis/parser/DoxygenParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue64657.txt
Labels: enhancement

#562 Improve error prone parser: skip warnings from javac
  src/main/java/edu/hm/hafner/analysis/parser/ErrorProneParser.java
  src/main/java/edu/hm/hafner/analysis/parser/GradleErrorProneParser.java
  src/test/java/edu/hm/hafner/analysis/parser/GradleErrorProneParserTest.java
Labels: bug

#569 IarParser - Map errors and fatal errors to severity ERROR
  src/main/java/edu/hm/hafner/analysis/parser/IarParser.java
  src/test/java/edu/hm/hafner/analysis/parser/IarParserTest.java
Labels: bug

#564 Rework pom to use Java 11 as minimum JDK development platform
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  Jenkinsfile
  pom.xml
  src/main/java/edu/hm/hafner/analysis/FileNameResolver.java
  src/main/java/edu/hm/hafner/analysis/FilteredLog.java
  src/main/java/edu/hm/hafner/analysis/IssueDifference.java
  src/main/java/edu/hm/hafner/analysis/LineRangeList.java
  src/main/java/edu/hm/hafner/analysis/Report.java
  src/main/java/edu/hm/hafner/analysis/parser/EclipseParser.java
  src/main/java/edu/hm/hafner/analysis/parser/JsonParser.java
  src/main/java/edu/hm/hafner/analysis/parser/QtTranslationParser.java
  src/main/java/edu/hm/hafner/analysis/parser/XmlParser.java
  src/main/java/edu/hm/hafner/analysis/parser/checkstyle/CheckStyleParser.java
  src/main/java/edu/hm/hafner/analysis/parser/pmd/PmdError.java
  src/test/java/edu/hm/hafner/analysis/AbstractParserTest.java
  src/test/java/edu/hm/hafner/analysis/FingerprintGeneratorBenchmark.java
  src/test/java/edu/hm/hafner/analysis/IssueDifferenceBenchmark.java
  src/test/java/edu/hm/hafner/analysis/PackageNameResolverBenchmark.java
Labels: internal

#560 [JENKINS-61939] Try to expose CppCheckAdapter bug with a test case
  src/test/java/edu/hm/hafner/analysis/parser/violations/CppCheckAdapterTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/violations/cpp-check-1.xml
  src/test/resources/edu/hm/hafner/analysis/parser/violations/cpp-check-2.xml
Labels: tests
