Repository jenkinsci/analysis-model, pull requests merged in 2021-11, with the labels that each got.

#702 Prevent XML external entity attacks (XXE)
  pom.xml
  src/main/java/edu/hm/hafner/analysis/SecureXmlParserFactory.java
  src/main/java/edu/hm/hafner/analysis/parser/checkstyle/TopicRule.java
Labels: bug

#701 [JENKINS-64284] Ignore `maven-javadoc-plugin` warnings in the `MavenConsoleParser`
  src/main/java/edu/hm/hafner/analysis/parser/MavenConsoleParser.java
  src/test/java/edu/hm/hafner/analysis/parser/MavenConsoleParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue64284.log
Labels: enhancement

#699 [JENKINS-56915] Fix Clang-Tidy reporting if line numbers are missing
  src/main/java/edu/hm/hafner/analysis/parser/ClangTidyParser.java
  src/test/java/edu/hm/hafner/analysis/parser/ClangTidyParserTest.java
  src/test/java/edu/hm/hafner/analysis/registry/ParsersTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/ClangTidy.txt
  src/test/resources/edu/hm/hafner/analysis/parser/issue56915.txt
Labels: bug

#707 Rename "C++ Lint" to Cpplint
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/parser/CppLintParser.java
  src/main/java/edu/hm/hafner/analysis/registry/CppLintDescriptor.java
Labels: documentation

#706 Add parser for codechecker
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/parser/CodeCheckerParser.java
  src/main/java/edu/hm/hafner/analysis/registry/CodeCheckerDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/test/java/edu/hm/hafner/analysis/parser/CodeCheckerParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/CodeChecker_with_linux_paths.txt
  src/test/resources/edu/hm/hafner/analysis/parser/CodeChecker_with_windows_paths.txt
Labels: feature

#708 Add OWASP dependency check issue parser
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/parser/OwaspDependencyCheckParser.java
  src/main/java/edu/hm/hafner/analysis/registry/OwaspDependencyCheckDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/test/java/edu/hm/hafner/analysis/parser/OwaspDependencyCheckParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/dependency-check-report.json
Labels: feature

#715 Add oelint test data with colour sequences
  SUPPORTED-FORMATS.md
  src/test/resources/edu/hm/hafner/analysis/parser/oelint-adv.txt
Labels: tests
