Repository jenkinsci/analysis-model, pull requests merged in 2022-07, with the labels that each got.

#811 Add ESLint icon
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/registry/EsLintDescriptor.java
Labels: enhancement

#812 Add Stylelint as additional alias for the CheckStyle parser
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/main/java/edu/hm/hafner/analysis/registry/StylelintDescriptor.java
  src/test/java/edu/hm/hafner/analysis/registry/ParsersTest.java
Labels: enhancement

#817 Add support for Revapi
  etc/Jenkinsfile.analysis
  pom.xml
  src/main/java/edu/hm/hafner/analysis/RevApiInfoExtension.java
  src/main/java/edu/hm/hafner/analysis/parser/RevApiParser.java
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/main/java/edu/hm/hafner/analysis/registry/RevApiDescriptor.java
  src/test/java/edu/hm/hafner/analysis/AbstractParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/DScannerParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/EclipseXMLParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/FlowParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/JsonParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/RevApiParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/StructuredFileParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/XmlParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/revapi_report.json
Labels: feature

#819 Fixing Trivy descriptions.
  src/main/java/edu/hm/hafner/analysis/parser/TrivyParser.java
Labels: internal
