Repository jenkinsci/analysis-model, pull requests merged in 2022-08, with the labels that each got.

#822 Improve Veracode parser
  src/main/java/edu/hm/hafner/analysis/parser/VeraCodePipelineScannerParser.java
  src/test/java/edu/hm/hafner/analysis/parser/VeraCodePipelineScannerParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/veracode_pipeline_scanner_result.json
Labels: enhancement

#824 [JENKINS-68969] Fix test error when compiling with JDK 17
  .github/workflows/ci.yml
  src/test/java/edu/hm/hafner/analysis/DuplicationGroupTest.java
Labels: tests

#825 [JENKINS-69242] Improve path detection during subdirectory traversal
  src/main/java/edu/hm/hafner/analysis/LookaheadParser.java
  src/test/java/edu/hm/hafner/analysis/parser/Gcc4CompilerParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue69242.txt
Labels: bug
