Repository jenkinsci/analysis-model, pull requests merged in 2023-10, with the labels that each got.

#952 [JENKINS-63580] Update regex for msbuild to recognize linker warnings
  src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java
  src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue63580.txt
Labels: bug, hacktoberfest

#953 Revert commons-io to 2.11.0
  pom.xml
Labels: bug

#957 Remove annotation-api dependency
  .github/workflows/ci.yml
  LICENSE
  README.md
  etc/assertj-templates/assertion_class_template.txt
  etc/assertj-templates/assertions_entry_point_class_template.txt
  etc/assertj-templates/soft_assertions_entry_point_class_template.txt
  pom.xml
Labels: internal

#964 Use separate versions of SpotBugs and PMD in API and Maven
  pom.xml
Labels: bug

#963 Change base branch name in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#968 Use ossrh for deployments
  SUPPORTED-FORMATS.md
  doc/dependency-graph.puml
  pom.xml
Labels: internal
