Repository jenkinsci/analysis-model, pull requests merged in 2023-07, with the labels that each got.

#925 Fix kotlin 1.8 warnings not detected
  src/main/java/edu/hm/hafner/analysis/parser/AbstractMavenLogParser.java
  src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java
  src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/kotlin-1_8.txt
Labels: enhancement

#932 Parallelize Tests
  pom.xml
Labels: tests

#933 Update the help text for the Pylint descriptor
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/registry/PyLintDescriptor.java
Labels: documentation

#934 [JENKINS-71687] Intellij IDEA Inspection causes Exception during Jenkins Job fix
  pom.xml
  src/main/java/edu/hm/hafner/analysis/parser/ClangAnalyzerPlistParser.java
  src/main/java/edu/hm/hafner/analysis/parser/FlawfinderParser.java
  src/main/java/edu/hm/hafner/analysis/parser/IdeaInspectionParser.java
  src/main/java/edu/hm/hafner/analysis/parser/StyleCopParser.java
  src/main/java/edu/hm/hafner/analysis/parser/XmlParser.java
  src/test/java/edu/hm/hafner/analysis/ArchitectureTest.java
  src/test/java/edu/hm/hafner/analysis/parser/IdeaInspectionParserTest.java
  src/test/resources/archunit_ignore_patterns.txt
  src/test/resources/edu/hm/hafner/analysis/parser/issue56235.xml
Labels: bug

#935 Add parser for grype report
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/Severity.java
  src/main/java/edu/hm/hafner/analysis/parser/GrypeParser.java
  src/main/java/edu/hm/hafner/analysis/registry/GrypeDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/test/java/edu/hm/hafner/analysis/parser/GrypeParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/grype-report.json
Labels: feature
