Repository jenkinsci/analysis-model, pull requests merged in 2023-01, with the labels that each got.

#865 Add Parser for Simulink Check tool
  SUPPORTED-FORMATS.md
  pom.xml
  src/main/java/edu/hm/hafner/analysis/parser/SimulinkCheckParser.java
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/main/java/edu/hm/hafner/analysis/registry/SimulinkCheckDescriptor.java
  src/test/java/edu/hm/hafner/analysis/parser/SimulinkCheckParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/Simulink.html
Labels: feature

#874 Add UNSPECIFIED and STYLE as a output from CodeChecker
  src/main/java/edu/hm/hafner/analysis/parser/CodeCheckerParser.java
  src/test/java/edu/hm/hafner/analysis/parser/CodeCheckerParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/CodeChecker_with_linux_paths.txt
Labels: enhancement

#877 Improve Java and JavaDoc parser by inspecting Maven module
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/LookaheadParser.java
  src/main/java/edu/hm/hafner/analysis/parser/AbstractMavenLogParser.java
  src/main/java/edu/hm/hafner/analysis/parser/AntJavacParser.java
  src/main/java/edu/hm/hafner/analysis/parser/JavaDocParser.java
  src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java
  src/main/java/edu/hm/hafner/analysis/parser/MavenConsoleParser.java
  src/test/java/edu/hm/hafner/analysis/parser/AntJavacParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/JavaDocParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue63346.log
Labels: bug, enhancement
