Repository jenkinsci/analysis-model, pull requests merged in 2023-11, with the labels that each got.

#973 Make descriptor classes package protected
  src/main/java/edu/hm/hafner/analysis/registry/CodeGeneratorDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/CrossCoreEmbeddedStudioDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/EmbeddedEngineerDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/FindBugsDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/GrypeDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/OwaspDependencyCheckDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/PnpmAuditDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/PolyspaceDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/RevApiDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/SimulinkCheckDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/ValgrindDescriptor.java
Labels: internal

#975 Update PMD logo location in SUPPORTED-FORMATS.md
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/registry/PmdDescriptor.java
Labels: documentation

#976 Updated logos and URLs in descriptors
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/registry/AnsibleLintDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/BluePearlDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/CargoDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/CmakeDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/DoxygenDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/MavenConsoleDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/MsBuildDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/MyPyDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/PnpmAuditDescriptor.java
Labels: documentation

#978 GrypeParser: added artifact name and type to report
  src/main/java/edu/hm/hafner/analysis/parser/GrypeParser.java
  src/test/java/edu/hm/hafner/analysis/parser/GrypeParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/grype-report.json
Labels: enhancement
