Repository jenkinsci/analysis-model, pull requests merged in 2023-09, with the labels that each got.

#939 Add category and type to code duplication issues
  src/main/java/edu/hm/hafner/analysis/parser/dry/AbstractDryParser.java
  src/main/java/edu/hm/hafner/analysis/parser/dry/cpd/CpdParser.java
  src/main/java/edu/hm/hafner/analysis/parser/dry/dupfinder/DupFinderParser.java
  src/main/java/edu/hm/hafner/analysis/parser/dry/simian/SimianParser.java
  src/test/java/edu/hm/hafner/analysis/parser/dry/cpd/CpdParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/dry/dupfinder/DupFinderParserTest.java
  src/test/java/edu/hm/hafner/analysis/parser/dry/simian/SimianParserTest.java
Labels: enhancement

#942 Allow developer control of parallel testing
  Jenkinsfile
  SUPPORTED-FORMATS.md
  pom.xml
Labels: internal

#944 [JENKINS-72011] Do not read from empty stream
  src/main/java/edu/hm/hafner/analysis/parser/AbstractMavenLogParser.java
  src/main/java/edu/hm/hafner/analysis/parser/MavenConsoleParser.java
  src/test/java/edu/hm/hafner/analysis/parser/MavenConsoleParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/enforcer-empty.txt
  src/test/resources/edu/hm/hafner/analysis/parser/issue72011.txt
Labels: bug

#738 Add valgrind parser
  SUPPORTED-FORMATS.md
  etc/Jenkinsfile.valgrind
  src/main/java/edu/hm/hafner/analysis/parser/violations/ValgrindAdapter.java
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/main/java/edu/hm/hafner/analysis/registry/ValgrindDescriptor.java
  src/test/java/edu/hm/hafner/analysis/parser/violations/ValgrindAdapterTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/violations/valgrind.xml
Labels: feature
