Repository jenkinsci/analysis-model, pull requests merged in 2024-09, with the labels that each got.

#1087 [JENKINS-73663] Fix pom flattening so that parent deps are included now
  pom.xml
Labels: bug

#1085 Add support for Yocto scanner
  src/main/java/edu/hm/hafner/analysis/parser/YoctoScannerParser.java
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/main/java/edu/hm/hafner/analysis/registry/YoctoScannerDescriptor.java
  src/test/java/edu/hm/hafner/analysis/parser/YoctoScannerParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/yocto_scanner_result.json
Labels: feature

#1091 Add ErrorProne to quality monitor
  .github/workflows/quality-monitor.yml
Labels: internal
