Repository jenkinsci/analysis-model, pull requests merged in 2024-11, with the labels that each got.

#1102 Sarif report: allow file paths in file URI scheme
  src/main/java/edu/hm/hafner/analysis/parser/violations/SarifAdapter.java
  src/test/java/edu/hm/hafner/analysis/parser/violations/SarifAdapterTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/violations/brokenfilePath.sarif
  src/test/resources/edu/hm/hafner/analysis/parser/violations/emptyfilePath.sarif
  src/test/resources/edu/hm/hafner/analysis/parser/violations/filePathInFileUriScheme.sarif
Labels: bug

#1112 Fix timeout problems in CI
  pom.xml
  src/test/java/edu/hm/hafner/analysis/parser/AntJavacParserTest.java
Labels: internal

#1110 Ignore suppressed issues in sarif reports
  src/main/java/edu/hm/hafner/analysis/parser/violations/SarifAdapter.java
  src/test/java/edu/hm/hafner/analysis/parser/violations/SarifAdapterTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/violations/suppressed-sarif.json
Labels: enhancement
