Repository jenkinsci/analysis-model, pull requests merged in 2024-01, with the labels that each got.

#991 Fix parsing for mixture of Kotlin and CMake output
  src/main/java/edu/hm/hafner/analysis/IssueBuilder.java
  src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/kotlin-cmake.txt
Labels: bug

#994 [EA] Add support for categories separated by a brace
  src/main/java/edu/hm/hafner/analysis/parser/EmbeddedEngineerParser.java
  src/test/java/edu/hm/hafner/analysis/parser/EmbeddedEngineerParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/ea.log
Labels: bug

#999 [JENKINS-70824] Add Bandit parser
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/parser/violations/BanditParserAdapter.java
  src/main/java/edu/hm/hafner/analysis/registry/BanditDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/test/java/edu/hm/hafner/analysis/parser/violations/BanditAdapterTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/violations/bandit.txt
Labels: feature

#998 [JENKINS-70996] Ignore directory messages from other tools
  src/main/java/edu/hm/hafner/analysis/IssueBuilder.java
  src/main/java/edu/hm/hafner/analysis/LookaheadParser.java
  src/test/java/edu/hm/hafner/analysis/parser/GccParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue70996.txt
Labels: bug

#1002 Add support for Code Climate
  src/main/java/edu/hm/hafner/analysis/parser/violations/CodeClimateAdapter.java
  src/main/java/edu/hm/hafner/analysis/registry/CodeClimateDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/test/java/edu/hm/hafner/analysis/parser/violations/CodeClimateAdapterTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/violations/code-climate.json
Labels: feature

#1003 [JENKINS-68415] Skip archives, jar-files and executables from fingerprinting
  src/main/java/edu/hm/hafner/analysis/FingerprintGenerator.java
  src/test/java/edu/hm/hafner/analysis/FingerprintGeneratorTest.java
Labels: enhancement

#1006 Mark issues that are part of changed code in the issue difference
  src/main/java/edu/hm/hafner/analysis/IssueDifference.java
  src/test/java/edu/hm/hafner/analysis/IssueDifferenceTest.java
Labels: enhancement

#1007 Use a flag to mark the issues that are part of modified code
  doc/dependency-graph.puml
  src/main/java/edu/hm/hafner/analysis/Issue.java
  src/main/java/edu/hm/hafner/analysis/IssueDifference.java
  src/main/java/edu/hm/hafner/analysis/IssuesInModifiedCodeMarker.java
  src/main/java/edu/hm/hafner/analysis/LineRange.java
  src/test/java/edu/hm/hafner/analysis/IssueDifferenceTest.java
  src/test/java/edu/hm/hafner/analysis/IssuesInModifiedCodeMarkerTest.java
  src/test/java/edu/hm/hafner/analysis/LineRangeTest.java
Labels: enhancement

#1009 Add a setter for the reference
  src/main/java/edu/hm/hafner/analysis/Report.java
  src/test/java/edu/hm/hafner/analysis/ReportTest.java
Labels: enhancement

#1010 Part of modified code not equals
  src/main/java/edu/hm/hafner/analysis/Issue.java
  src/main/java/edu/hm/hafner/analysis/IssueBuilder.java
  src/main/java/edu/hm/hafner/analysis/Report.java
  src/test/java/edu/hm/hafner/analysis/IssueTest.java
  src/test/java/edu/hm/hafner/analysis/ReportTest.java
Labels: enhancement

#1011 Automatically update supported formats after each commit
  .github/workflows/update-badges.yml
  SUPPORTED-FORMATS.md
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/test/java/edu/hm/hafner/analysis/registry/ParserRegistryTest.java
  src/test/java/edu/hm/hafner/analysis/registry/UpdateSupportedFormats.java
Labels: internal
