Repository jenkinsci/analysis-model, pull requests merged in 2024-04, with the labels that each got.

#1050 Use the PMD square image.
  src/main/java/edu/hm/hafner/analysis/registry/PmdDescriptor.java
Labels: documentation

#1055 Use the new square SVG image for PMD results
  src/main/java/edu/hm/hafner/analysis/registry/PmdDescriptor.java
Labels: documentation

#1040 [JENKINS-72887] Add coverity parser
  src/main/java/edu/hm/hafner/analysis/parser/violations/CoverityAdapter.java
  src/main/java/edu/hm/hafner/analysis/registry/CoverityDescriptor.java
  src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
  src/test/java/edu/hm/hafner/analysis/parser/violations/CoverityAdapterTest.java
  src/test/java/edu/hm/hafner/analysis/registry/AbstractParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/violations/coverity.json
Labels: enhancement

#1058 Skip subreport messages when copying and merging reports
  src/main/java/edu/hm/hafner/analysis/Report.java
  src/test/java/edu/hm/hafner/analysis/ReportTest.java
Labels: bug
