Repository jenkinsci/analysis-model, pull requests merged in 2025-02, with the labels that each got.

#1136 Added methods to configure context lines in FullTextFingerprint
  src/main/java/edu/hm/hafner/analysis/FullTextFingerprint.java
  src/test/java/edu/hm/hafner/analysis/FingerprintGeneratorTest.java
  src/test/java/edu/hm/hafner/analysis/FullTextFingerprintTest.java
Labels: enhancement

#1145 [Jenkins-70153] Add support for gradle build-tools warnings (w:)
  src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java
  src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue70153.txt
Labels: enhancement

#1146 Write the latest version of the library as property into the POM
  pom.xml
Labels: internal

#1147 [JENKINS-68744] Do not ignore long lines while parsing MSBuild warning logs
  src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java
  src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue68744.txt
Labels: bug

#1148 [JENKINS-70065] Should recognize Armcc5 warnings while parsing.
  src/main/java/edu/hm/hafner/analysis/parser/Armcc5CompilerParser.java
  src/test/java/edu/hm/hafner/analysis/parser/Armcc5CompilerParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue70065.txt
Labels: enhancement

#1149 [JENKINS-61855] Add Support for Doxygen Warnings.
  src/main/java/edu/hm/hafner/analysis/parser/DoxygenParser.java
  src/main/java/edu/hm/hafner/analysis/parser/Gcc4CompilerParser.java
  src/test/java/edu/hm/hafner/analysis/parser/DoxygenParserTest.java
  src/test/resources/edu/hm/hafner/analysis/parser/issue61855.txt
Labels: bug
